// Lists the English strings the UI asks for, so the translation maps can be
// filled in.
//
// The lookup is keyed by English text rather than an invented key, which buys
// English-without-a-map and a graceful fallback for untranslated strings, at
// the cost of making a typo silent: `t('Cancle')` type-checks and simply does
// not translate. This script is the safety net for that trade-off. It reports
// keys with no translation yet, so a mistake surfaces as a missing entry rather
// than as untranslated UI nobody notices.
//
//   dart run tool/extract_strings.dart          # keys missing from any map
//   dart run tool/extract_strings.dart --all    # every key, with use counts
//   dart run tool/extract_strings.dart --stats  # per-language totals
//   dart run tool/extract_strings.dart --markdown > l10n/TRANSLATION_KEYS.md
import 'dart:io';

/// Every way a literal English string reaches the translation store:
///   t('Cancel')             one-off copy
///   .t('Cancel')            the same, chained
///   label: 'Dashboard',     DrawerDestination English source text
///   'In Stock': '...',      a key in a translation map
/// All are literals, so a text scrape is enough and no Dart parsing is needed.
final _call = RegExp(r"\.t\(\s*'([^']*)'\s*\)");
final _label = RegExp(r"^\s*label:\s*'([^']*)'\s*,\s*$", multiLine: true);
final _mapEntry = RegExp(r"^\s*'([^']*)'\s*:", multiLine: true);

const langs = ['myanmar', 'thai', 'japanese'];

/// Rejects symbols, paths, placeholders and Dart identifiers.
bool looksLikeProse(String key) {
  if (key.isEmpty || key.length > 120) return false;
  if (RegExp(r"""[{}'"`$/\\]""").hasMatch(key)) return false;
  // Must contain a real letter, including non-ASCII scripts.
  if (!RegExp(r'[A-Za-z\u0080-\uFFFF]').hasMatch(key)) return false;
  // A lone lowercase identifier is code, not copy: `onTap`, `v1`, `showDialog`.
  if (RegExp(r'^[a-z_][A-Za-z0-9_]*$').hasMatch(key)) return false;
  return true;
}

List<File> dartFiles(Directory root) => root
    .listSync(recursive: true)
    .whereType<File>()
    .where((f) => f.path.endsWith('.dart'))
    .toList();

void main(List<String> args) {
  final lib = Directory('lib');
  if (!lib.existsSync()) {
    stderr.writeln('run from the package root');
    exit(1);
  }

  final counts = <String, int>{};
  // Where each key is used, so the generated checklist can point a translator at
  // the screen a string belongs to. `lib/features/<feature>/...` is the group.
  final sources = <String, Set<String>>{};
  for (final file in dartFiles(lib)) {
    // The maps hold translations, not requests for them.
    if (file.path.contains(RegExp(r'l10n[\\/]strings'))) continue;
    final String text;
    try {
      text = file.readAsStringSync();
    } on IOException {
      continue;
    }
    for (final match in [..._call.allMatches(text), ..._label.allMatches(text)]) {
      final key = (match.group(1) ?? '').trim().replaceAll(RegExp(r'\s+'), ' ');
      if (!looksLikeProse(key)) continue;
      counts[key] = (counts[key] ?? 0) + text.split("'$key'").length - 1;
      (sources[key] ??= <String>{}).add(file.path.replaceAll('\\', '/'));
    }
  }

  if (counts.isEmpty) {
    stderr.writeln('no translatable strings found');
    exit(1);
  }

  final keys = counts.keys.toList()..sort();

  if (args.contains('--all')) {
    for (final key in keys) {
      stdout.writeln('[${counts[key]!.toString().padLeft(3)}] $key');
    }
    stdout.writeln('total: ${keys.length}');
    return;
  }

  if (args.contains('--markdown')) {
    // Grouped by feature so a translator can work one area at a time. A key
    // used from two features is listed under both, with every location.
    final groups = <String, Set<String>>{};
    for (final key in keys) {
      for (final path in sources[key]!) {
        final group = path.startsWith('lib/features/')
            ? 'lib/features/${path.split('/')[2]}'
            : path.split('/').take(3).join('/');
        (groups[group] ??= <String>{}).add(key);
      }
    }
    stdout.writeln('# Translation keys\n');
    stdout.writeln(
      'Generated by `dart run tool/extract_strings.dart --markdown`. '
      'Do not edit by hand.\n',
    );
    stdout.writeln('Translations live in the maps, not in this file:\n');
    for (final lang in langs) {
      stdout.writeln('- `lib/shared/l10n/strings/$lang.dart`');
    }
    stdout.writeln(
      '\nThe English string is the lookup key, so an entry that is missing or '
      'misspelled falls back to English rather than failing to build. '
      '`{v1}`, `{v2}` are runtime values: keep them, in that order, in every '
      'language. Keep numerals Western, and do not shorten the English: Thai '
      'and Burmese both need more room than English in places, and Burmese '
      'renders taller at the same font size.\n',
    );
    for (final group in groups.keys.toList()..sort()) {
      stdout.writeln('## $group\n');
      for (final key in (groups[group]!.toList()..sort())) {
        final where = (sources[key]!)
            .where((p) => p.startsWith(group) || !group.startsWith('lib/features'))
            .map((p) => p.split('/').last)
            .toSet()
            .toList()
          ..sort();
        stdout.writeln('- [ ] `$key` &mdash; ${where.join(', ')}');
      }
      stdout.writeln('');
    }
    stdout.writeln('_${keys.length} keys total._');
    return;
  }

  final maps = <String, Set<String>>{};
  for (final lang in langs) {
    final file = File('lib/shared/l10n/strings/$lang.dart');
    maps[lang] = file.existsSync()
        ? _mapEntry
              .allMatches(file.readAsStringSync())
              .map((m) => m.group(1)!)
              .toSet()
        : <String>{};
  }

  if (args.contains('--stats')) {
    for (final lang in langs) {
      final done = maps[lang]!.length;
      final pct = keys.isEmpty ? 0 : (done * 100 / keys.length).round();
      stdout.writeln('${lang.padRight(9)} $done / ${keys.length}  ($pct%)');
    }
    return;
  }

  var missing = 0;
  for (final key in keys) {
    for (final lang in langs) {
      if (!maps[lang]!.contains(key)) {
        missing++;
        stdout.writeln('$lang\t$key');
      }
    }
  }
  stderr.writeln(
    '\n${keys.length} keys, '
    '${maps.values.fold(0, (a, s) => a + s.length)} entries across '
    '${langs.length} maps, $missing missing',
  );
}
